use_frameworks!

platform :ios, '8.0'

target 'MobileSpeedLib_Example' do
  pod 'MobileSpeedLib', :path => '../'

  target 'MobileSpeedLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
